In [1]:
import numpy as np

Consider the below code to answer further questions:

In [2]:
import numpy as np

list_ = ["1", "2" , "3" , "4" , "5" ]

array_list = np.array(object = list_)

#### Q1. Is there any difference in the data type of variables list_ and array_list? If there is then write a code to print the data types of both the variables.

In [3]:
# Yes there is a difference

print(type(list_))

print(type(array_list))

<class 'list'>
<class 'numpy.ndarray'>


#### Q2. Write a code to print the data type of each and every element of both the variables list_ and arra_list.

In [4]:
print(list_)

for i in list_:
    print(type(i))

print(array_list)

for i in array_list:
    print(type(i))

['1', '2', '3', '4', '5']
<class 'str'>
<class 'str'>
<class 'str'>
<class 'str'>
<class 'str'>
['1' '2' '3' '4' '5']
<class 'numpy.str_'>
<class 'numpy.str_'>
<class 'numpy.str_'>
<class 'numpy.str_'>
<class 'numpy.str_'>


#### Q3. Considering the following changes in the variable, array_list:

array_list = np.array(object = list_, dtype = int)

Will there be any difference in the data type of the elements present in both the variables, list_ and
arra_list? If so then print the data types of each and every element present in both the variables, list_
and arra_list.

In [5]:
array_list = np.array(object = list_, dtype = int)

In [6]:
# yes there is a change.

print(list_)

for i in list_:
    print(type(i))

print(array_list)

for i in array_list:
    print(type(i))

['1', '2', '3', '4', '5']
<class 'str'>
<class 'str'>
<class 'str'>
<class 'str'>
<class 'str'>
[1 2 3 4 5]
<class 'numpy.int32'>
<class 'numpy.int32'>
<class 'numpy.int32'>
<class 'numpy.int32'>
<class 'numpy.int32'>


Consider the below code to answer further questions:

import numpy as np

num_list = [ [ 1 , 2 , 3 ] , [ 4 , 5 , 6 ] ]

num_array = np.array(object = num_list)


Q4. Write a code to find the following characteristics of variable, num_array:
(i) shape
(ii) size

In [7]:
import numpy as np

num_list = [ [ 1 , 2 , 3 ] , [ 4 , 5 , 6 ] ]

num_array = np.array(object = num_list)

In [8]:
print(num_array.shape) # It will reprensents the shape of the array ( rows and columns)

(2, 3)


In [9]:
print(num_array.size) # size represents the number of elements present in the array.

6


#### Q5. Write a code to create numpy array of 3*3 matrix containing zeros only, using a numpy array creation function.

[Hint: The size of the array will be 9 and the shape will be (3,3).]

In [10]:
print(np.zeros((3,3)))

# or

print(np.random.randint(0,1,(3,3)))

[[0. 0. 0.]
 [0. 0. 0.]
 [0. 0. 0.]]
[[0 0 0]
 [0 0 0]
 [0 0 0]]


#### Q6. Create an identity matrix of shape (5,5) using numpy functions?

[Hint: An identity matrix is a matrix containing 1 diagonally and other elements will be 0.]

In [11]:
print(np.identity(5,dtype=int))

[[1 0 0 0 0]
 [0 1 0 0 0]
 [0 0 1 0 0]
 [0 0 0 1 0]
 [0 0 0 0 1]]
